language: python

python:
  - "3.6"      # current default Python on Travis CI

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - pytest

# public environment variables
# env:
#   - MYVAR=VALUE
#     MYVAR2='MY LONG VALUE'
