language: python

python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - pytest

# public environment variables
env:
  - FLASK_APP=flaskr
    FLASK_ENV=development
